### ISSUE TITLE
Domain vxfacebook.live not resolving

### ISSUE THREAD

**Issue by rafitamolin** [AliZad64/FacebookFix#23]

**Comment by AliZad64** [comment]
Hello rafitamolin

Thanks for the Issue. I apologize for the inconvenience. The server was down due to an expired subscription, but I've now turned it back on. However, I had to reduce deploy pricing. This may result in slower load times or occasional outages.

Thank you for your patience and understanding during this time.

**Comment by rafitamolin** [comment]
Thanks a lot for your hard work :)
